# .github/workflows/release.yml

name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger on tags like v1.2.3
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+' # Trigger on tags like v1.2.3rc1
  workflow_dispatch:

permissions:
  # Required for Trusted Publishing using OIDC
  id-token: write
  # Optional: Allow action to create release on GitHub
  # contents: write


jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest


    steps:
      - name: Check out repository code at the tag
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create venv and Install build dependencies
        run: |
          echo "Creating venv with Python version: ${{ steps.setup.outputs.python-version }}"
          uv venv
          source .venv/bin/activate
          echo "Installing build tools..."
          uv pip install build twine
          echo "Build tools installed."

      - name: Build source distribution and wheel
        run: |
          source .venv/bin/activate
          echo "Building distributions..."
          python -m build
          echo "Distributions built."
          ls -l dist/

      - name: Verify built distributions (Optional but Recommended)
        run: |
          source .venv/bin/activate
          echo "Checking distributions with twine..."
          twine check dist/*
          echo "Twine check complete."

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Use TestPyPI for testing
          repository-url: https://test.pypi.org/legacy/
          # Attestations enabled by default when password is not set

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag' && !contains(github.ref_name, 'a') && !contains(github.ref_name, 'b') && !contains(github.ref_name, 'rc')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          # Attestations enabled by default when password is not set
